/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ResourceRow } from "./components/luster-resource-table/luster-resource-table";
import { TabItem } from "./components/luster-tabs/luster-tabs";
export { ResourceRow } from "./components/luster-resource-table/luster-resource-table";
export { TabItem } from "./components/luster-tabs/luster-tabs";
export namespace Components {
    interface LusterAccordion {
        /**
          * @default ''
         */
        "badge": string;
        /**
          * @default 'default'
         */
        "badgeVariant": 'primary' | 'default' | 'success' | 'beta';
        /**
          * @default false
         */
        "expanded": boolean;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default ''
         */
        "subtitle": string;
    }
    interface LusterActivityItem {
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default false
         */
        "downloadable": boolean;
        /**
          * @default ''
         */
        "fileSize": string;
        /**
          * @default 'edit'
         */
        "icon": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "time": string;
        /**
          * @default 'activity'
         */
        "variant": 'activity' | 'file';
    }
    interface LusterAlert {
        /**
          * @default true
         */
        "dismissible": boolean;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default ''
         */
        "timestamp": string;
        /**
          * @default 'info'
         */
        "variant": 'info' | 'success' | 'warning' | 'error';
    }
    interface LusterArticleCard {
        /**
          * @default ''
         */
        "author": string;
        /**
          * @default ''
         */
        "authorRole": string;
        /**
          * @default ''
         */
        "category": string;
        /**
          * @default ''
         */
        "date": string;
        /**
          * @default ''
         */
        "excerpt": string;
        /**
          * @default false
         */
        "featured": boolean;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default ''
         */
        "imageUrl": string;
    }
    interface LusterBadge {
        /**
          * @default false
         */
        "dot": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'primary' | 'success' | 'warning' | 'error' | 'beta' | 'live';
    }
    interface LusterButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'tertiary' | 'destructive';
    }
    interface LusterCard {
        /**
          * @default false
         */
        "hoverable": boolean;
        /**
          * @default 'md'
         */
        "padding": 'sm' | 'md' | 'lg' | 'none';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'elevated' | 'glass' | 'feature';
    }
    interface LusterCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "indeterminate": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface LusterColorSwatch {
        /**
          * @default '#a3a6ff'
         */
        "color": string;
        /**
          * @default ''
         */
        "hex": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface LusterFeatureQuote {
        /**
          * @default ''
         */
        "author": string;
        /**
          * @default ''
         */
        "quote": string;
        /**
          * @default ''
         */
        "role": string;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'large' | 'inline';
    }
    interface LusterHero {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default ''
         */
        "imageUrl": string;
        /**
          * @default false
         */
        "parallax": boolean;
        /**
          * @default ''
         */
        "section": string;
        /**
          * @default ''
         */
        "subtitle": string;
    }
    interface LusterInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "error": boolean;
        /**
          * @default ''
         */
        "errorMessage": string;
        /**
          * @default ''
         */
        "helperText": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface LusterModal {
        /**
          * @default 'Cancel'
         */
        "cancelLabel": string;
        /**
          * @default 'Proceed'
         */
        "confirmLabel": string;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "subtitle": string;
    }
    interface LusterNavbar {
        /**
          * @default 'explorer'
         */
        "activeLink": string;
        /**
          * @default 'EDITORIAL SYSTEM'
         */
        "logoSub": string;
        /**
          * @default 'The Digital Curator'
         */
        "logoTitle": string;
    }
    interface LusterProfileCard {
        /**
          * @default ''
         */
        "avatar": string;
        /**
          * @default 'View Portfolio'
         */
        "ctaLabel": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "role": string;
        /**
          * @default ''
         */
        "stat1Label": string;
        /**
          * @default ''
         */
        "stat1Value": string;
        /**
          * @default ''
         */
        "stat2Label": string;
        /**
          * @default ''
         */
        "stat2Value": string;
    }
    interface LusterResourceTable {
        /**
          * @default '[]'
         */
        "rows": ResourceRow[] | string;
    }
    interface LusterSidebar {
        /**
          * @default 'foundations'
         */
        "active": string;
    }
    interface LusterStatCard {
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default false
         */
        "hasToggle": boolean;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default ''
         */
        "icon": string;
        /**
          * @default 'active'
         */
        "status": 'active' | 'beta' | 'deprecated';
        /**
          * @default false
         */
        "toggleOn": boolean;
        /**
          * @default ''
         */
        "users": string;
        /**
          * @default ''
         */
        "version": string;
    }
    interface LusterTabs {
        /**
          * @default ''
         */
        "active": string;
        /**
          * @default ''
         */
        "tabs": TabItem[] | string;
    }
    interface LusterToggle {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
    }
}
export interface LusterAccordionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterAccordionElement;
}
export interface LusterAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterAlertElement;
}
export interface LusterButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterButtonElement;
}
export interface LusterCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterCheckboxElement;
}
export interface LusterInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterInputElement;
}
export interface LusterModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterModalElement;
}
export interface LusterSidebarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterSidebarElement;
}
export interface LusterTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterTabsElement;
}
export interface LusterToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLusterToggleElement;
}
declare global {
    interface HTMLLusterAccordionElementEventMap {
        "dcToggle": boolean;
    }
    interface HTMLLusterAccordionElement extends Components.LusterAccordion, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterAccordionElementEventMap>(type: K, listener: (this: HTMLLusterAccordionElement, ev: LusterAccordionCustomEvent<HTMLLusterAccordionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterAccordionElementEventMap>(type: K, listener: (this: HTMLLusterAccordionElement, ev: LusterAccordionCustomEvent<HTMLLusterAccordionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterAccordionElement: {
        prototype: HTMLLusterAccordionElement;
        new (): HTMLLusterAccordionElement;
    };
    interface HTMLLusterActivityItemElement extends Components.LusterActivityItem, HTMLStencilElement {
    }
    var HTMLLusterActivityItemElement: {
        prototype: HTMLLusterActivityItemElement;
        new (): HTMLLusterActivityItemElement;
    };
    interface HTMLLusterAlertElementEventMap {
        "dcDismiss": void;
    }
    interface HTMLLusterAlertElement extends Components.LusterAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterAlertElementEventMap>(type: K, listener: (this: HTMLLusterAlertElement, ev: LusterAlertCustomEvent<HTMLLusterAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterAlertElementEventMap>(type: K, listener: (this: HTMLLusterAlertElement, ev: LusterAlertCustomEvent<HTMLLusterAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterAlertElement: {
        prototype: HTMLLusterAlertElement;
        new (): HTMLLusterAlertElement;
    };
    interface HTMLLusterArticleCardElement extends Components.LusterArticleCard, HTMLStencilElement {
    }
    var HTMLLusterArticleCardElement: {
        prototype: HTMLLusterArticleCardElement;
        new (): HTMLLusterArticleCardElement;
    };
    interface HTMLLusterBadgeElement extends Components.LusterBadge, HTMLStencilElement {
    }
    var HTMLLusterBadgeElement: {
        prototype: HTMLLusterBadgeElement;
        new (): HTMLLusterBadgeElement;
    };
    interface HTMLLusterButtonElementEventMap {
        "dcClick": void;
    }
    interface HTMLLusterButtonElement extends Components.LusterButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterButtonElementEventMap>(type: K, listener: (this: HTMLLusterButtonElement, ev: LusterButtonCustomEvent<HTMLLusterButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterButtonElementEventMap>(type: K, listener: (this: HTMLLusterButtonElement, ev: LusterButtonCustomEvent<HTMLLusterButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterButtonElement: {
        prototype: HTMLLusterButtonElement;
        new (): HTMLLusterButtonElement;
    };
    interface HTMLLusterCardElement extends Components.LusterCard, HTMLStencilElement {
    }
    var HTMLLusterCardElement: {
        prototype: HTMLLusterCardElement;
        new (): HTMLLusterCardElement;
    };
    interface HTMLLusterCheckboxElementEventMap {
        "dcChange": boolean;
    }
    interface HTMLLusterCheckboxElement extends Components.LusterCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterCheckboxElementEventMap>(type: K, listener: (this: HTMLLusterCheckboxElement, ev: LusterCheckboxCustomEvent<HTMLLusterCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterCheckboxElementEventMap>(type: K, listener: (this: HTMLLusterCheckboxElement, ev: LusterCheckboxCustomEvent<HTMLLusterCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterCheckboxElement: {
        prototype: HTMLLusterCheckboxElement;
        new (): HTMLLusterCheckboxElement;
    };
    interface HTMLLusterColorSwatchElement extends Components.LusterColorSwatch, HTMLStencilElement {
    }
    var HTMLLusterColorSwatchElement: {
        prototype: HTMLLusterColorSwatchElement;
        new (): HTMLLusterColorSwatchElement;
    };
    interface HTMLLusterFeatureQuoteElement extends Components.LusterFeatureQuote, HTMLStencilElement {
    }
    var HTMLLusterFeatureQuoteElement: {
        prototype: HTMLLusterFeatureQuoteElement;
        new (): HTMLLusterFeatureQuoteElement;
    };
    interface HTMLLusterHeroElement extends Components.LusterHero, HTMLStencilElement {
    }
    var HTMLLusterHeroElement: {
        prototype: HTMLLusterHeroElement;
        new (): HTMLLusterHeroElement;
    };
    interface HTMLLusterInputElementEventMap {
        "dcChange": string;
        "dcInput": string;
        "dcFocus": void;
        "dcBlur": void;
    }
    interface HTMLLusterInputElement extends Components.LusterInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterInputElementEventMap>(type: K, listener: (this: HTMLLusterInputElement, ev: LusterInputCustomEvent<HTMLLusterInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterInputElementEventMap>(type: K, listener: (this: HTMLLusterInputElement, ev: LusterInputCustomEvent<HTMLLusterInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterInputElement: {
        prototype: HTMLLusterInputElement;
        new (): HTMLLusterInputElement;
    };
    interface HTMLLusterModalElementEventMap {
        "dcClose": void;
        "dcConfirm": void;
    }
    interface HTMLLusterModalElement extends Components.LusterModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterModalElementEventMap>(type: K, listener: (this: HTMLLusterModalElement, ev: LusterModalCustomEvent<HTMLLusterModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterModalElementEventMap>(type: K, listener: (this: HTMLLusterModalElement, ev: LusterModalCustomEvent<HTMLLusterModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterModalElement: {
        prototype: HTMLLusterModalElement;
        new (): HTMLLusterModalElement;
    };
    interface HTMLLusterNavbarElement extends Components.LusterNavbar, HTMLStencilElement {
    }
    var HTMLLusterNavbarElement: {
        prototype: HTMLLusterNavbarElement;
        new (): HTMLLusterNavbarElement;
    };
    interface HTMLLusterProfileCardElement extends Components.LusterProfileCard, HTMLStencilElement {
    }
    var HTMLLusterProfileCardElement: {
        prototype: HTMLLusterProfileCardElement;
        new (): HTMLLusterProfileCardElement;
    };
    interface HTMLLusterResourceTableElement extends Components.LusterResourceTable, HTMLStencilElement {
    }
    var HTMLLusterResourceTableElement: {
        prototype: HTMLLusterResourceTableElement;
        new (): HTMLLusterResourceTableElement;
    };
    interface HTMLLusterSidebarElementEventMap {
        "dcNavChange": string;
    }
    interface HTMLLusterSidebarElement extends Components.LusterSidebar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterSidebarElementEventMap>(type: K, listener: (this: HTMLLusterSidebarElement, ev: LusterSidebarCustomEvent<HTMLLusterSidebarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterSidebarElementEventMap>(type: K, listener: (this: HTMLLusterSidebarElement, ev: LusterSidebarCustomEvent<HTMLLusterSidebarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterSidebarElement: {
        prototype: HTMLLusterSidebarElement;
        new (): HTMLLusterSidebarElement;
    };
    interface HTMLLusterStatCardElement extends Components.LusterStatCard, HTMLStencilElement {
    }
    var HTMLLusterStatCardElement: {
        prototype: HTMLLusterStatCardElement;
        new (): HTMLLusterStatCardElement;
    };
    interface HTMLLusterTabsElementEventMap {
        "dcTabChange": string;
    }
    interface HTMLLusterTabsElement extends Components.LusterTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterTabsElementEventMap>(type: K, listener: (this: HTMLLusterTabsElement, ev: LusterTabsCustomEvent<HTMLLusterTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterTabsElementEventMap>(type: K, listener: (this: HTMLLusterTabsElement, ev: LusterTabsCustomEvent<HTMLLusterTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterTabsElement: {
        prototype: HTMLLusterTabsElement;
        new (): HTMLLusterTabsElement;
    };
    interface HTMLLusterToggleElementEventMap {
        "dcChange": boolean;
    }
    interface HTMLLusterToggleElement extends Components.LusterToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLusterToggleElementEventMap>(type: K, listener: (this: HTMLLusterToggleElement, ev: LusterToggleCustomEvent<HTMLLusterToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLusterToggleElementEventMap>(type: K, listener: (this: HTMLLusterToggleElement, ev: LusterToggleCustomEvent<HTMLLusterToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLusterToggleElement: {
        prototype: HTMLLusterToggleElement;
        new (): HTMLLusterToggleElement;
    };
    interface HTMLElementTagNameMap {
        "luster-accordion": HTMLLusterAccordionElement;
        "luster-activity-item": HTMLLusterActivityItemElement;
        "luster-alert": HTMLLusterAlertElement;
        "luster-article-card": HTMLLusterArticleCardElement;
        "luster-badge": HTMLLusterBadgeElement;
        "luster-button": HTMLLusterButtonElement;
        "luster-card": HTMLLusterCardElement;
        "luster-checkbox": HTMLLusterCheckboxElement;
        "luster-color-swatch": HTMLLusterColorSwatchElement;
        "luster-feature-quote": HTMLLusterFeatureQuoteElement;
        "luster-hero": HTMLLusterHeroElement;
        "luster-input": HTMLLusterInputElement;
        "luster-modal": HTMLLusterModalElement;
        "luster-navbar": HTMLLusterNavbarElement;
        "luster-profile-card": HTMLLusterProfileCardElement;
        "luster-resource-table": HTMLLusterResourceTableElement;
        "luster-sidebar": HTMLLusterSidebarElement;
        "luster-stat-card": HTMLLusterStatCardElement;
        "luster-tabs": HTMLLusterTabsElement;
        "luster-toggle": HTMLLusterToggleElement;
    }
}
declare namespace LocalJSX {
    interface LusterAccordion {
        /**
          * @default ''
         */
        "badge"?: string;
        /**
          * @default 'default'
         */
        "badgeVariant"?: 'primary' | 'default' | 'success' | 'beta';
        /**
          * @default false
         */
        "expanded"?: boolean;
        /**
          * @default ''
         */
        "heading"?: string;
        "onDcToggle"?: (event: LusterAccordionCustomEvent<boolean>) => void;
        /**
          * @default ''
         */
        "subtitle"?: string;
    }
    interface LusterActivityItem {
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default false
         */
        "downloadable"?: boolean;
        /**
          * @default ''
         */
        "fileSize"?: string;
        /**
          * @default 'edit'
         */
        "icon"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "time"?: string;
        /**
          * @default 'activity'
         */
        "variant"?: 'activity' | 'file';
    }
    interface LusterAlert {
        /**
          * @default true
         */
        "dismissible"?: boolean;
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * @default ''
         */
        "message"?: string;
        "onDcDismiss"?: (event: LusterAlertCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "timestamp"?: string;
        /**
          * @default 'info'
         */
        "variant"?: 'info' | 'success' | 'warning' | 'error';
    }
    interface LusterArticleCard {
        /**
          * @default ''
         */
        "author"?: string;
        /**
          * @default ''
         */
        "authorRole"?: string;
        /**
          * @default ''
         */
        "category"?: string;
        /**
          * @default ''
         */
        "date"?: string;
        /**
          * @default ''
         */
        "excerpt"?: string;
        /**
          * @default false
         */
        "featured"?: boolean;
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * @default ''
         */
        "imageUrl"?: string;
    }
    interface LusterBadge {
        /**
          * @default false
         */
        "dot"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'primary' | 'success' | 'warning' | 'error' | 'beta' | 'live';
    }
    interface LusterButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        "onDcClick"?: (event: LusterButtonCustomEvent<void>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'destructive';
    }
    interface LusterCard {
        /**
          * @default false
         */
        "hoverable"?: boolean;
        /**
          * @default 'md'
         */
        "padding"?: 'sm' | 'md' | 'lg' | 'none';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'elevated' | 'glass' | 'feature';
    }
    interface LusterCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onDcChange"?: (event: LusterCheckboxCustomEvent<boolean>) => void;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface LusterColorSwatch {
        /**
          * @default '#a3a6ff'
         */
        "color"?: string;
        /**
          * @default ''
         */
        "hex"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface LusterFeatureQuote {
        /**
          * @default ''
         */
        "author"?: string;
        /**
          * @default ''
         */
        "quote"?: string;
        /**
          * @default ''
         */
        "role"?: string;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'large' | 'inline';
    }
    interface LusterHero {
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * @default ''
         */
        "imageUrl"?: string;
        /**
          * @default false
         */
        "parallax"?: boolean;
        /**
          * @default ''
         */
        "section"?: string;
        /**
          * @default ''
         */
        "subtitle"?: string;
    }
    interface LusterInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "error"?: boolean;
        /**
          * @default ''
         */
        "errorMessage"?: string;
        /**
          * @default ''
         */
        "helperText"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onDcBlur"?: (event: LusterInputCustomEvent<void>) => void;
        "onDcChange"?: (event: LusterInputCustomEvent<string>) => void;
        "onDcFocus"?: (event: LusterInputCustomEvent<void>) => void;
        "onDcInput"?: (event: LusterInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface LusterModal {
        /**
          * @default 'Cancel'
         */
        "cancelLabel"?: string;
        /**
          * @default 'Proceed'
         */
        "confirmLabel"?: string;
        /**
          * @default ''
         */
        "heading"?: string;
        "onDcClose"?: (event: LusterModalCustomEvent<void>) => void;
        "onDcConfirm"?: (event: LusterModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "subtitle"?: string;
    }
    interface LusterNavbar {
        /**
          * @default 'explorer'
         */
        "activeLink"?: string;
        /**
          * @default 'EDITORIAL SYSTEM'
         */
        "logoSub"?: string;
        /**
          * @default 'The Digital Curator'
         */
        "logoTitle"?: string;
    }
    interface LusterProfileCard {
        /**
          * @default ''
         */
        "avatar"?: string;
        /**
          * @default 'View Portfolio'
         */
        "ctaLabel"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default ''
         */
        "role"?: string;
        /**
          * @default ''
         */
        "stat1Label"?: string;
        /**
          * @default ''
         */
        "stat1Value"?: string;
        /**
          * @default ''
         */
        "stat2Label"?: string;
        /**
          * @default ''
         */
        "stat2Value"?: string;
    }
    interface LusterResourceTable {
        /**
          * @default '[]'
         */
        "rows"?: ResourceRow[] | string;
    }
    interface LusterSidebar {
        /**
          * @default 'foundations'
         */
        "active"?: string;
        "onDcNavChange"?: (event: LusterSidebarCustomEvent<string>) => void;
    }
    interface LusterStatCard {
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default false
         */
        "hasToggle"?: boolean;
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * @default ''
         */
        "icon"?: string;
        /**
          * @default 'active'
         */
        "status"?: 'active' | 'beta' | 'deprecated';
        /**
          * @default false
         */
        "toggleOn"?: boolean;
        /**
          * @default ''
         */
        "users"?: string;
        /**
          * @default ''
         */
        "version"?: string;
    }
    interface LusterTabs {
        /**
          * @default ''
         */
        "active"?: string;
        "onDcTabChange"?: (event: LusterTabsCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "tabs"?: TabItem[] | string;
    }
    interface LusterToggle {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onDcChange"?: (event: LusterToggleCustomEvent<boolean>) => void;
    }

    interface LusterAccordionAttributes {
        "heading": string;
        "subtitle": string;
        "badge": string;
        "badgeVariant": 'primary' | 'default' | 'success' | 'beta';
        "expanded": boolean;
    }
    interface LusterActivityItemAttributes {
        "label": string;
        "description": string;
        "time": string;
        "variant": 'activity' | 'file';
        "icon": string;
        "fileSize": string;
        "downloadable": boolean;
    }
    interface LusterAlertAttributes {
        "heading": string;
        "message": string;
        "variant": 'info' | 'success' | 'warning' | 'error';
        "dismissible": boolean;
        "timestamp": string;
    }
    interface LusterArticleCardAttributes {
        "category": string;
        "heading": string;
        "excerpt": string;
        "date": string;
        "author": string;
        "authorRole": string;
        "imageUrl": string;
        "featured": boolean;
    }
    interface LusterBadgeAttributes {
        "variant": 'default' | 'primary' | 'success' | 'warning' | 'error' | 'beta' | 'live';
        "dot": boolean;
        "size": 'sm' | 'md';
    }
    interface LusterButtonAttributes {
        "variant": 'primary' | 'secondary' | 'tertiary' | 'destructive';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "loading": boolean;
        "fullWidth": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface LusterCardAttributes {
        "variant": 'default' | 'elevated' | 'glass' | 'feature';
        "padding": 'sm' | 'md' | 'lg' | 'none';
        "hoverable": boolean;
    }
    interface LusterCheckboxAttributes {
        "label": string;
        "checked": boolean;
        "disabled": boolean;
        "indeterminate": boolean;
        "value": string;
    }
    interface LusterColorSwatchAttributes {
        "color": string;
        "name": string;
        "hex": string;
        "size": 'sm' | 'md' | 'lg';
    }
    interface LusterFeatureQuoteAttributes {
        "quote": string;
        "author": string;
        "role": string;
        "variant": 'default' | 'large' | 'inline';
    }
    interface LusterHeroAttributes {
        "heading": string;
        "subtitle": string;
        "section": string;
        "imageUrl": string;
        "parallax": boolean;
    }
    interface LusterInputAttributes {
        "label": string;
        "placeholder": string;
        "value": string;
        "type": string;
        "error": boolean;
        "errorMessage": string;
        "helperText": string;
        "disabled": boolean;
        "readonly": boolean;
        "name": string;
    }
    interface LusterModalAttributes {
        "open": boolean;
        "heading": string;
        "subtitle": string;
        "confirmLabel": string;
        "cancelLabel": string;
        "size": 'sm' | 'md' | 'lg';
    }
    interface LusterNavbarAttributes {
        "logoTitle": string;
        "logoSub": string;
        "activeLink": string;
    }
    interface LusterProfileCardAttributes {
        "name": string;
        "role": string;
        "avatar": string;
        "stat1Value": string;
        "stat1Label": string;
        "stat2Value": string;
        "stat2Label": string;
        "ctaLabel": string;
    }
    interface LusterResourceTableAttributes {
        "rows": ResourceRow[] | string;
    }
    interface LusterSidebarAttributes {
        "active": string;
    }
    interface LusterStatCardAttributes {
        "heading": string;
        "description": string;
        "version": string;
        "status": 'active' | 'beta' | 'deprecated';
        "users": string;
        "hasToggle": boolean;
        "toggleOn": boolean;
        "icon": string;
    }
    interface LusterTabsAttributes {
        "tabs": TabItem[] | string;
        "active": string;
    }
    interface LusterToggleAttributes {
        "label": string;
        "checked": boolean;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "luster-accordion": Omit<LusterAccordion, keyof LusterAccordionAttributes> & { [K in keyof LusterAccordion & keyof LusterAccordionAttributes]?: LusterAccordion[K] } & { [K in keyof LusterAccordion & keyof LusterAccordionAttributes as `attr:${K}`]?: LusterAccordionAttributes[K] } & { [K in keyof LusterAccordion & keyof LusterAccordionAttributes as `prop:${K}`]?: LusterAccordion[K] };
        "luster-activity-item": Omit<LusterActivityItem, keyof LusterActivityItemAttributes> & { [K in keyof LusterActivityItem & keyof LusterActivityItemAttributes]?: LusterActivityItem[K] } & { [K in keyof LusterActivityItem & keyof LusterActivityItemAttributes as `attr:${K}`]?: LusterActivityItemAttributes[K] } & { [K in keyof LusterActivityItem & keyof LusterActivityItemAttributes as `prop:${K}`]?: LusterActivityItem[K] };
        "luster-alert": Omit<LusterAlert, keyof LusterAlertAttributes> & { [K in keyof LusterAlert & keyof LusterAlertAttributes]?: LusterAlert[K] } & { [K in keyof LusterAlert & keyof LusterAlertAttributes as `attr:${K}`]?: LusterAlertAttributes[K] } & { [K in keyof LusterAlert & keyof LusterAlertAttributes as `prop:${K}`]?: LusterAlert[K] };
        "luster-article-card": Omit<LusterArticleCard, keyof LusterArticleCardAttributes> & { [K in keyof LusterArticleCard & keyof LusterArticleCardAttributes]?: LusterArticleCard[K] } & { [K in keyof LusterArticleCard & keyof LusterArticleCardAttributes as `attr:${K}`]?: LusterArticleCardAttributes[K] } & { [K in keyof LusterArticleCard & keyof LusterArticleCardAttributes as `prop:${K}`]?: LusterArticleCard[K] };
        "luster-badge": Omit<LusterBadge, keyof LusterBadgeAttributes> & { [K in keyof LusterBadge & keyof LusterBadgeAttributes]?: LusterBadge[K] } & { [K in keyof LusterBadge & keyof LusterBadgeAttributes as `attr:${K}`]?: LusterBadgeAttributes[K] } & { [K in keyof LusterBadge & keyof LusterBadgeAttributes as `prop:${K}`]?: LusterBadge[K] };
        "luster-button": Omit<LusterButton, keyof LusterButtonAttributes> & { [K in keyof LusterButton & keyof LusterButtonAttributes]?: LusterButton[K] } & { [K in keyof LusterButton & keyof LusterButtonAttributes as `attr:${K}`]?: LusterButtonAttributes[K] } & { [K in keyof LusterButton & keyof LusterButtonAttributes as `prop:${K}`]?: LusterButton[K] };
        "luster-card": Omit<LusterCard, keyof LusterCardAttributes> & { [K in keyof LusterCard & keyof LusterCardAttributes]?: LusterCard[K] } & { [K in keyof LusterCard & keyof LusterCardAttributes as `attr:${K}`]?: LusterCardAttributes[K] } & { [K in keyof LusterCard & keyof LusterCardAttributes as `prop:${K}`]?: LusterCard[K] };
        "luster-checkbox": Omit<LusterCheckbox, keyof LusterCheckboxAttributes> & { [K in keyof LusterCheckbox & keyof LusterCheckboxAttributes]?: LusterCheckbox[K] } & { [K in keyof LusterCheckbox & keyof LusterCheckboxAttributes as `attr:${K}`]?: LusterCheckboxAttributes[K] } & { [K in keyof LusterCheckbox & keyof LusterCheckboxAttributes as `prop:${K}`]?: LusterCheckbox[K] };
        "luster-color-swatch": Omit<LusterColorSwatch, keyof LusterColorSwatchAttributes> & { [K in keyof LusterColorSwatch & keyof LusterColorSwatchAttributes]?: LusterColorSwatch[K] } & { [K in keyof LusterColorSwatch & keyof LusterColorSwatchAttributes as `attr:${K}`]?: LusterColorSwatchAttributes[K] } & { [K in keyof LusterColorSwatch & keyof LusterColorSwatchAttributes as `prop:${K}`]?: LusterColorSwatch[K] };
        "luster-feature-quote": Omit<LusterFeatureQuote, keyof LusterFeatureQuoteAttributes> & { [K in keyof LusterFeatureQuote & keyof LusterFeatureQuoteAttributes]?: LusterFeatureQuote[K] } & { [K in keyof LusterFeatureQuote & keyof LusterFeatureQuoteAttributes as `attr:${K}`]?: LusterFeatureQuoteAttributes[K] } & { [K in keyof LusterFeatureQuote & keyof LusterFeatureQuoteAttributes as `prop:${K}`]?: LusterFeatureQuote[K] };
        "luster-hero": Omit<LusterHero, keyof LusterHeroAttributes> & { [K in keyof LusterHero & keyof LusterHeroAttributes]?: LusterHero[K] } & { [K in keyof LusterHero & keyof LusterHeroAttributes as `attr:${K}`]?: LusterHeroAttributes[K] } & { [K in keyof LusterHero & keyof LusterHeroAttributes as `prop:${K}`]?: LusterHero[K] };
        "luster-input": Omit<LusterInput, keyof LusterInputAttributes> & { [K in keyof LusterInput & keyof LusterInputAttributes]?: LusterInput[K] } & { [K in keyof LusterInput & keyof LusterInputAttributes as `attr:${K}`]?: LusterInputAttributes[K] } & { [K in keyof LusterInput & keyof LusterInputAttributes as `prop:${K}`]?: LusterInput[K] };
        "luster-modal": Omit<LusterModal, keyof LusterModalAttributes> & { [K in keyof LusterModal & keyof LusterModalAttributes]?: LusterModal[K] } & { [K in keyof LusterModal & keyof LusterModalAttributes as `attr:${K}`]?: LusterModalAttributes[K] } & { [K in keyof LusterModal & keyof LusterModalAttributes as `prop:${K}`]?: LusterModal[K] };
        "luster-navbar": Omit<LusterNavbar, keyof LusterNavbarAttributes> & { [K in keyof LusterNavbar & keyof LusterNavbarAttributes]?: LusterNavbar[K] } & { [K in keyof LusterNavbar & keyof LusterNavbarAttributes as `attr:${K}`]?: LusterNavbarAttributes[K] } & { [K in keyof LusterNavbar & keyof LusterNavbarAttributes as `prop:${K}`]?: LusterNavbar[K] };
        "luster-profile-card": Omit<LusterProfileCard, keyof LusterProfileCardAttributes> & { [K in keyof LusterProfileCard & keyof LusterProfileCardAttributes]?: LusterProfileCard[K] } & { [K in keyof LusterProfileCard & keyof LusterProfileCardAttributes as `attr:${K}`]?: LusterProfileCardAttributes[K] } & { [K in keyof LusterProfileCard & keyof LusterProfileCardAttributes as `prop:${K}`]?: LusterProfileCard[K] };
        "luster-resource-table": Omit<LusterResourceTable, keyof LusterResourceTableAttributes> & { [K in keyof LusterResourceTable & keyof LusterResourceTableAttributes]?: LusterResourceTable[K] } & { [K in keyof LusterResourceTable & keyof LusterResourceTableAttributes as `attr:${K}`]?: LusterResourceTableAttributes[K] } & { [K in keyof LusterResourceTable & keyof LusterResourceTableAttributes as `prop:${K}`]?: LusterResourceTable[K] };
        "luster-sidebar": Omit<LusterSidebar, keyof LusterSidebarAttributes> & { [K in keyof LusterSidebar & keyof LusterSidebarAttributes]?: LusterSidebar[K] } & { [K in keyof LusterSidebar & keyof LusterSidebarAttributes as `attr:${K}`]?: LusterSidebarAttributes[K] } & { [K in keyof LusterSidebar & keyof LusterSidebarAttributes as `prop:${K}`]?: LusterSidebar[K] };
        "luster-stat-card": Omit<LusterStatCard, keyof LusterStatCardAttributes> & { [K in keyof LusterStatCard & keyof LusterStatCardAttributes]?: LusterStatCard[K] } & { [K in keyof LusterStatCard & keyof LusterStatCardAttributes as `attr:${K}`]?: LusterStatCardAttributes[K] } & { [K in keyof LusterStatCard & keyof LusterStatCardAttributes as `prop:${K}`]?: LusterStatCard[K] };
        "luster-tabs": Omit<LusterTabs, keyof LusterTabsAttributes> & { [K in keyof LusterTabs & keyof LusterTabsAttributes]?: LusterTabs[K] } & { [K in keyof LusterTabs & keyof LusterTabsAttributes as `attr:${K}`]?: LusterTabsAttributes[K] } & { [K in keyof LusterTabs & keyof LusterTabsAttributes as `prop:${K}`]?: LusterTabs[K] };
        "luster-toggle": Omit<LusterToggle, keyof LusterToggleAttributes> & { [K in keyof LusterToggle & keyof LusterToggleAttributes]?: LusterToggle[K] } & { [K in keyof LusterToggle & keyof LusterToggleAttributes as `attr:${K}`]?: LusterToggleAttributes[K] } & { [K in keyof LusterToggle & keyof LusterToggleAttributes as `prop:${K}`]?: LusterToggle[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "luster-accordion": LocalJSX.IntrinsicElements["luster-accordion"] & JSXBase.HTMLAttributes<HTMLLusterAccordionElement>;
            "luster-activity-item": LocalJSX.IntrinsicElements["luster-activity-item"] & JSXBase.HTMLAttributes<HTMLLusterActivityItemElement>;
            "luster-alert": LocalJSX.IntrinsicElements["luster-alert"] & JSXBase.HTMLAttributes<HTMLLusterAlertElement>;
            "luster-article-card": LocalJSX.IntrinsicElements["luster-article-card"] & JSXBase.HTMLAttributes<HTMLLusterArticleCardElement>;
            "luster-badge": LocalJSX.IntrinsicElements["luster-badge"] & JSXBase.HTMLAttributes<HTMLLusterBadgeElement>;
            "luster-button": LocalJSX.IntrinsicElements["luster-button"] & JSXBase.HTMLAttributes<HTMLLusterButtonElement>;
            "luster-card": LocalJSX.IntrinsicElements["luster-card"] & JSXBase.HTMLAttributes<HTMLLusterCardElement>;
            "luster-checkbox": LocalJSX.IntrinsicElements["luster-checkbox"] & JSXBase.HTMLAttributes<HTMLLusterCheckboxElement>;
            "luster-color-swatch": LocalJSX.IntrinsicElements["luster-color-swatch"] & JSXBase.HTMLAttributes<HTMLLusterColorSwatchElement>;
            "luster-feature-quote": LocalJSX.IntrinsicElements["luster-feature-quote"] & JSXBase.HTMLAttributes<HTMLLusterFeatureQuoteElement>;
            "luster-hero": LocalJSX.IntrinsicElements["luster-hero"] & JSXBase.HTMLAttributes<HTMLLusterHeroElement>;
            "luster-input": LocalJSX.IntrinsicElements["luster-input"] & JSXBase.HTMLAttributes<HTMLLusterInputElement>;
            "luster-modal": LocalJSX.IntrinsicElements["luster-modal"] & JSXBase.HTMLAttributes<HTMLLusterModalElement>;
            "luster-navbar": LocalJSX.IntrinsicElements["luster-navbar"] & JSXBase.HTMLAttributes<HTMLLusterNavbarElement>;
            "luster-profile-card": LocalJSX.IntrinsicElements["luster-profile-card"] & JSXBase.HTMLAttributes<HTMLLusterProfileCardElement>;
            "luster-resource-table": LocalJSX.IntrinsicElements["luster-resource-table"] & JSXBase.HTMLAttributes<HTMLLusterResourceTableElement>;
            "luster-sidebar": LocalJSX.IntrinsicElements["luster-sidebar"] & JSXBase.HTMLAttributes<HTMLLusterSidebarElement>;
            "luster-stat-card": LocalJSX.IntrinsicElements["luster-stat-card"] & JSXBase.HTMLAttributes<HTMLLusterStatCardElement>;
            "luster-tabs": LocalJSX.IntrinsicElements["luster-tabs"] & JSXBase.HTMLAttributes<HTMLLusterTabsElement>;
            "luster-toggle": LocalJSX.IntrinsicElements["luster-toggle"] & JSXBase.HTMLAttributes<HTMLLusterToggleElement>;
        }
    }
}
